# Báo cáo bài tập thực hành tuần 1  
> Họ và tên: Nguyễn Vạn Phúc Huy <br>
> MSSV: 23110163 <br>
> Lớp: 23TTH (Chiều thứ 6, ca 1)

Import các thư viện cần thiết

In [20]:
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import StandardScaler, KBinsDiscretizer, MinMaxScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

Note: Câu 1 không giải thích nhiều vì làm lại y chang trong file pdf

### 1. Làm sạch và tiền xử lý dữ liệu:

Như yêu cầu nên sẽ không giải thích chi tiết các bước làm sạch và tiền xử lý dữ liệu, chỉ trình bày code thực hiện.

### 2. Bài tập vận dụng

Đọc dữ liệu trực tiếp link đã cung cấp thay vì tải về vì em lười ...

In [32]:
link_hd_ko_che= r'https://archive.ics.uci.edu/ml/machine-learning-databases/arrhythmia/arrhythmia.data'
df = pd.read_csv(link_hd_ko_che, header=None)
df


,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,1
448,37,0,190,85,100,137,361,201,73,86,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,10
449,36,0,166,68,108,176,365,194,116,-85,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,2
450,32,1,155,55,93,106,386,218,63,54,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,1


Hiện thị thông tin tổng quan bộ dữ liệu

In [33]:
df.info()
df.describe()
print(df.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Columns: 280 entries, 0 to 279
dtypes: float64(120), int64(155), object(5)
memory usage: 988.9+ KB
0        int64
1        int64
2        int64
3        int64
4        int64
        ...   
275    float64
276    float64
277    float64
278    float64
279      int64
Length: 280, dtype: object


Ta thực hiện làm sạch dữ liệu bằng cách loại bỏ các dòng có giá trị thiếu và các dòng có giá trị trùng lặp (nếu có)

In [34]:
print(df.isnull().sum())
df = df.dropna()

df


0      0
1      0
2      0
3      0
4      0
      ..
275    0
276    0
277    0
278    0
279    0
Length: 280, dtype: int64


,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,1
448,37,0,190,85,100,137,361,201,73,86,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,10
449,36,0,166,68,108,176,365,194,116,-85,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,2
450,32,1,155,55,93,106,386,218,63,54,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,1


In [35]:

print(df.duplicated().sum())
df = df.drop_duplicates()
df

0


,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,1
448,37,0,190,85,100,137,361,201,73,86,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,10
449,36,0,166,68,108,176,365,194,116,-85,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,2
450,32,1,155,55,93,106,386,218,63,54,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,1


Tiếp theo thì ta scaler dữ liệu để chuẩn hóa dữ liệu về cùng một thang đo

In [36]:
scaler = StandardScaler()
array = df.values

robust_array = scaler.fit_transform(array)
robust_df = pd.DataFrame(robust_array, columns=df.columns)


ValueError: could not convert string to float: '?'

Ta thấy dòng code ở trên bị lỗi không chạy với error như sau
```python
ValueError: could not convert string to float: '?'
``` 
Nên ta thực hiện lọc '?'

In [ ]:
(df== '?').any().value_counts()

df.replace('?', 0, inplace=True)

Loại bỏ các outliers

In [ ]:
scaler = StandardScaler()
array = df.values

robust_array = scaler.fit_transform(array)
robust_df = pd.DataFrame(robust_array, columns=df.columns)

print('Loai bo cac outliers: \n', robust_df)

Loai bo cac outliers: 
           0         1         2         3         4         5         6    \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
..        ...       ...       ...       ...       ...       ...       ...   
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560   
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154   
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209   
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505   
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195   

          7         8         9    ...       270   

Chuẩn hóa và scaling dữ liệu bằng pp z-score và pp min-max

In [ ]:
# phuong pháp StandardScaler
scaler = StandardScaler()
array = df.values

standard = scaler.fit_transform(array)
standard_df = pd.DataFrame(standard, columns=df.columns)
print('Chuan hoa du lieu:\n', standard_df)

Chuan hoa du lieu:
           0         1         2         3         4         5         6    \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
..        ...       ...       ...       ...       ...       ...       ...   
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560   
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154   
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209   
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505   
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195   

          7         8         9    ...       270       

In [ ]:
# phương pháp MinMaxScaler
scaler = MinMaxScaler()
minmax = scaler.fit_transform(array)
minmax_df = pd.DataFrame(minmax, index = df.index)
print('Scaling dữ liệu:\n',minmax_df)

Scaling dữ liệu:
           0    1         2         3         4         5         6    \
0    0.903614  0.0  0.125926  0.435294  0.270677  0.368321  0.501805   
1    0.674699  1.0  0.088889  0.341176  0.195489  0.332061  0.610108   
2    0.650602  0.0  0.099259  0.523529  0.624060  0.311069  0.555957   
3    0.662651  0.0  0.103704  0.517647  0.338346  0.385496  0.534296   
4    0.903614  0.0  0.125926  0.435294  0.248120  0.345420  0.462094   
..        ...  ...       ...       ...       ...       ...       ...   
447  0.638554  1.0  0.081481  0.376471  0.187970  0.379771  0.541516   
448  0.445783  0.0  0.125926  0.464706  0.338346  0.261450  0.465704   
449  0.433735  0.0  0.090370  0.364706  0.398496  0.335878  0.480144   
450  0.385542  1.0  0.074074  0.288235  0.285714  0.202290  0.555957   
451  0.939759  1.0  0.081481  0.376471  0.180451  0.242366  0.476534   

          7         8         9    ...       270       271       272  273  \
0    0.241758  0.590244  0.457478  ...  

Rời rác hóa mỗi thuộc tính số hóa thành
- 10 equi-width ranges
- 10 equi-depth ranges

In [ ]:
equi_width_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='uniform')
equi_width_data = equi_width_scaler.fit_transform(df)
equi_width_data

c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:342: UserWarning: Feature 19 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:342: UserWarning: Feature 67 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:342: UserWarning: Feature 69 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:342: UserWarning: Feature 83 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:342: UserWarning: Feature 131 is constant and will be replaced with 0.
  warn

array([[9., 0., 1., ..., 5., 5., 4.],
       [6., 9., 0., ..., 4., 5., 3.],
       [6., 0., 0., ..., 4., 5., 6.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [3., 9., 0., ..., 5., 5., 0.],
       [9., 9., 0., ..., 4., 4., 0.]], shape=(452, 280))

Ta thấy có dòng báo lỗi như sau 
```python
c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:342: UserWarning: Feature 274 is constant and will be replaced with 0.
  warnings.warn(f"Feature {i} is constant and will be replaced with 0.")
```
Vì vậy nên ta sẽ tiến hành loại bỏ các cột có toàn giá trị 0 trước khi rời rác hóa.

In [ ]:

zeros_cols = df.columns[(df == 0).all()]
df.drop(labels=zeros_cols, inplace=True, axis=1)

equi_width_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='uniform')
equi_width_data = equi_width_scaler.fit_transform(df)
equi_width_data


array([[9., 0., 1., ..., 5., 5., 4.],
       [6., 9., 0., ..., 4., 5., 3.],
       [6., 0., 0., ..., 4., 5., 6.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [3., 9., 0., ..., 5., 5., 0.],
       [9., 9., 0., ..., 4., 4., 0.]], shape=(452, 263))

In [ ]:
equi_depth_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='quantile')
equi_depth_data = equi_width_scaler.fit_transform(df)
equi_depth_data


array([[9., 0., 1., ..., 5., 5., 4.],
       [6., 9., 0., ..., 4., 5., 3.],
       [6., 0., 0., ..., 4., 5., 6.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [3., 9., 0., ..., 5., 5., 0.],
       [9., 9., 0., ..., 4., 4., 0.]], shape=(452, 263))

### 3. PCA

Ta thực hiện nạp dữ liệu

In [ ]:

df2 = pd.read_csv(r'C:\Users\lenovo\OneDrive\Document\Data-Mining_MTH10358\Homeworks\TH\1\musk+version+2\clean2.data', header=None, delimiter=',')
df2

,0,1,2,3,4,5,6,7,8,9,...,159,160,161,162,163,164,165,166,167,168
0,MUSK-211,211_1+1,46,-108,-60,-69,-117,49,38,-161,...,-308,52,-7,39,126,156,-50,-112,96,1.0
1,MUSK-211,211_1+10,41,-188,-145,22,-117,-6,57,-171,...,-59,-2,52,103,136,169,-61,-136,79,1.0
2,MUSK-211,211_1+11,46,-194,-145,28,-117,73,57,-168,...,-134,-154,57,143,142,165,-67,-145,39,1.0
3,MUSK-211,211_1+12,41,-188,-145,22,-117,-7,57,-170,...,-60,-4,52,104,136,168,-60,-135,80,1.0
4,MUSK-211,211_1+13,41,-188,-145,22,-117,-7,57,-170,...,-60,-4,52,104,137,168,-60,-135,80,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6593,NON-MUSK-jp13,jp13_2+5,51,-123,-23,-108,-117,134,-160,82,...,-66,164,-14,-29,107,171,-44,-115,118,0.0
6594,NON-MUSK-jp13,jp13_2+6,44,-104,-19,-105,-117,142,-165,68,...,-51,166,-9,150,129,158,-66,-144,-5,0.0
6595,NON-MUSK-jp13,jp13_2+7,44,-102,-19,-104,-117,72,-165,65,...,90,117,-8,150,130,159,-66,-144,-6,0.0
6596,NON-MUSK-jp13,jp13_2+8,51,-121,-23,-106,-117,63,-161,79,...,86,99,-14,-31,106,171,-44,-116,117,0.0


Hiện thị thông tin tổng quan bộ dữ liệu

In [39]:
df2.info()
df2.describe()
print(df.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6598 entries, 0 to 6597
Columns: 169 entries, 0 to 168
dtypes: float64(1), int64(166), object(2)
memory usage: 8.5+ MB
0        int64
1        int64
2        int64
3        int64
4        int64
        ...   
275    float64
276    float64
277    float64
278    float64
279      int64
Length: 280, dtype: object


 Xóa 2 cột đầu vì 2 cột đầu ta không có dùng đến

In [40]:
df2 = df2.iloc[:, 2:]
df2

,2,3,4,5,6,7,8,9,10,11,...,159,160,161,162,163,164,165,166,167,168
0,46,-108,-60,-69,-117,49,38,-161,-8,5,...,-308,52,-7,39,126,156,-50,-112,96,1.0
1,41,-188,-145,22,-117,-6,57,-171,-39,-100,...,-59,-2,52,103,136,169,-61,-136,79,1.0
2,46,-194,-145,28,-117,73,57,-168,-39,-22,...,-134,-154,57,143,142,165,-67,-145,39,1.0
3,41,-188,-145,22,-117,-7,57,-170,-39,-99,...,-60,-4,52,104,136,168,-60,-135,80,1.0
4,41,-188,-145,22,-117,-7,57,-170,-39,-99,...,-60,-4,52,104,137,168,-60,-135,80,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6593,51,-123,-23,-108,-117,134,-160,82,-230,-28,...,-66,164,-14,-29,107,171,-44,-115,118,0.0
6594,44,-104,-19,-105,-117,142,-165,68,-225,-32,...,-51,166,-9,150,129,158,-66,-144,-5,0.0
6595,44,-102,-19,-104,-117,72,-165,65,-219,-12,...,90,117,-8,150,130,159,-66,-144,-6,0.0
6596,51,-121,-23,-106,-117,63,-161,79,-224,-30,...,86,99,-14,-31,106,171,-44,-116,117,0.0


Ta thực hiện kiểm tra xem dữ liệu có bị trùng hay không, nếu có thì ta sẽ loại bỏ các dòng trùng lặp đó đi

In [41]:
df2.isnull().sum().sort_values(ascending=False)

2      0
3      0
4      0
5      0
6      0
      ..
164    0
165    0
166    0
167    0
168    0
Length: 167, dtype: int64

Tương tự, ta cũng sẽ loại bỏ các dòng có giá trị thiếu đi vì nếu để lại thì sẽ ảnh hưởng đến kết quả PCA

In [ ]:
((df2 == '?') == True).sum().sort_values(ascending=False)


2      0
3      0
4      0
5      0
6      0
      ..
164    0
165    0
166    0
167    0
168    0
Length: 167, dtype: int64

Tiếp theo ta lọc những dòng có giá trị không phải là số vì nếu để lại thì sẽ ảnh hưởng đến kết quả PCA

In [ ]:
df2_pca = df2.select_dtypes(exclude='object')

df2_pca = df2_pca[df2_pca.columns[:-1]]
df2_pca


,2,3,4,5,6,7,8,9,10,11,...,158,159,160,161,162,163,164,165,166,167
0,46,-108,-60,-69,-117,49,38,-161,-8,5,...,-244,-308,52,-7,39,126,156,-50,-112,96
1,41,-188,-145,22,-117,-6,57,-171,-39,-100,...,-235,-59,-2,52,103,136,169,-61,-136,79
2,46,-194,-145,28,-117,73,57,-168,-39,-22,...,-238,-134,-154,57,143,142,165,-67,-145,39
3,41,-188,-145,22,-117,-7,57,-170,-39,-99,...,-236,-60,-4,52,104,136,168,-60,-135,80
4,41,-188,-145,22,-117,-7,57,-170,-39,-99,...,-236,-60,-4,52,104,137,168,-60,-135,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6593,51,-123,-23,-108,-117,134,-160,82,-230,-28,...,62,-66,164,-14,-29,107,171,-44,-115,118
6594,44,-104,-19,-105,-117,142,-165,68,-225,-32,...,60,-51,166,-9,150,129,158,-66,-144,-5
6595,44,-102,-19,-104,-117,72,-165,65,-219,-12,...,-226,90,117,-8,150,130,159,-66,-144,-6
6596,51,-121,-23,-106,-117,63,-161,79,-224,-30,...,-238,86,99,-14,-31,106,171,-44,-116,117


Thực hiện PCA để giảm chiều dữ liệu bằng cách sử dụng thư viện PCA của sklearn

In [54]:
pca = PCA()
pca_result = pca.fit_transform(df2_pca) 
pca_result

array([[-9.99463932e+01, -9.15817180e+02,  1.66686603e+02, ...,
        -2.00926382e+00,  6.49157635e-01,  9.22882593e-01],
       [ 2.08960040e+02, -8.28276632e+02,  7.17301732e+01, ...,
         8.50205472e-01, -6.72083911e-01,  8.79635949e-01],
       [ 2.50215211e+02, -7.95425387e+02, -2.01909466e+02, ...,
         2.67714147e-01,  1.28962297e+00,  1.16115622e+00],
       ...,
       [-9.70255709e+02,  1.37261091e+02, -3.67097607e+02, ...,
         5.39309269e+00,  8.16562866e-01,  1.65866567e+00],
       [-9.77148961e+02,  7.27506558e+01,  2.19302370e+02, ...,
         4.85167274e+00,  2.18189232e-01,  2.27511531e+00],
       [-8.98429502e+02,  1.66629988e+02,  2.08679827e+02, ...,
         3.16500000e-01,  5.76085154e-01,  7.32136474e-01]],
      shape=(6598, 166))

Ta thực hiện lấy giá trị eigenvalues và eigenvectors của ma trận covariance

In [53]:
eigenvectors = pca.components_
eigenvectors

array([[-2.97137514e-03, -7.06755098e-02, -7.91938565e-02, ...,
        -1.41749460e-03, -1.22433553e-02,  3.08829012e-03],
       [-5.69905035e-02,  2.42059127e-02,  3.49982033e-02, ...,
        -3.62576743e-02, -6.48892199e-02,  2.32312750e-02],
       [-4.08873101e-03,  1.20755542e-01,  7.75935347e-03, ...,
         2.66274637e-02,  1.81740219e-02,  1.69540247e-01],
       ...,
       [ 5.77812789e-03, -1.01891098e-02,  8.55698836e-02, ...,
         6.55551196e-04,  1.29948160e-03,  2.40306043e-04],
       [-6.53473282e-05, -4.66232514e-02, -3.47297288e-01, ...,
        -5.53501371e-04,  2.01937322e-03,  1.89670467e-04],
       [-1.30070912e-03, -5.96284763e-03, -1.02747769e-01, ...,
         8.14628951e-04, -1.55090624e-03,  7.69406910e-04]],
      shape=(166, 166))

In [50]:
eigen_values = np.square(pca.singular_values_)
eigen_values

array([3.00856869e+09, 1.70131869e+09, 5.00545894e+08, 3.03600798e+08,
       2.66840040e+08, 2.42452867e+08, 2.18125877e+08, 1.95551382e+08,
       1.67567178e+08, 1.59276140e+08, 1.27371946e+08, 1.18028904e+08,
       1.09542021e+08, 9.67449368e+07, 9.08952479e+07, 8.31696975e+07,
       7.75477812e+07, 7.09509848e+07, 6.10519026e+07, 5.96363685e+07,
       5.22180399e+07, 4.88041822e+07, 4.70140808e+07, 4.13277464e+07,
       3.62898059e+07, 3.59992110e+07, 3.52245456e+07, 3.30178651e+07,
       3.15269171e+07, 2.95502446e+07, 2.79135395e+07, 2.58060669e+07,
       2.47067783e+07, 2.29102832e+07, 2.24117704e+07, 2.09947458e+07,
       2.03357313e+07, 1.80377011e+07, 1.71562259e+07, 1.68244965e+07,
       1.52702182e+07, 1.46858833e+07, 1.37139738e+07, 1.27864116e+07,
       1.22622407e+07, 1.16869181e+07, 1.10112318e+07, 1.02234310e+07,
       9.55199051e+06, 9.03817751e+06, 8.72733735e+06, 8.31821227e+06,
       7.90212493e+06, 7.50435397e+06, 7.46891743e+06, 7.41877288e+06,
      